import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';import vm from 'node:vm';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'christmas-vote-'));fs.copyFileSync('server.mjs',path.join(dir,'server.mjs'));fs.copyFileSync('index.html',path.join(dir,'index.html'));new vm.Script(fs.readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1]);
let child;async function start(){child=spawn(process.execPath,[path.join(dir,'server.mjs')],{env:{...process.env,PORT:'3097'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>reject(Error('Server exited: '+code)));});}async function stop(){const ended=new Promise(resolve=>child.once('exit',resolve));child.kill();await ended;}const base='http://localhost:3097';async function get(){return (await fetch(base+'/api/state')).json();}async function post(route,body,cookie){const res=await fetch(base+route,{method:'POST',headers:{Origin:base,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(body)});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};}
try{
await start();assert.equal((await get()).phase,'setup');
assert.equal((await post('/api/admin',{action:'open-nominations'})).status,200);
assert.equal((await post('/api/admin',{action:'close-nominations'})).status,400);
let nomination=await post('/api/vote',{venue:'A'});assert.equal(nomination.status,200);
assert.equal((await post('/api/vote',{venue:'B'},nomination.cookie)).status,409);
for(const venue of [' a ','B','B','C','D','E','F'])assert.equal((await post('/api/vote',{venue})).status,200);
assert.equal((await get()).nominationTotals,null);
await post('/api/admin',{action:'close-nominations'});
assert.deepEqual((await get()).nominationTotals,[2,2,1,1,1,1]);
assert.equal((await post('/api/admin',{action:'open-shortlist',selected:[1,2,3,4,5]})).status,400);
assert.equal((await post('/api/admin',{action:'open-shortlist',selected:[0,1]})).status,200);
assert.deepEqual((await get()).venues,['A','B']);
let vote=await post('/api/vote',{choices:[1]});assert.equal(vote.status,200);
assert.equal((await get()).venueTotals,null);assert.equal((await post('/api/vote',{choices:[0]},vote.cookie)).status,409);
await stop();await start();assert.equal((await get()).venueCount,1);
assert.equal((await post('/api/admin',{action:'close-venue'})).status,200);
assert.deepEqual((await get()).venueTotals,[0,1]);assert.equal((await post('/api/vote',{choices:[1]})).status,409);
const dates=['2026-12-04','2026-12-11','2026-12-18'];
assert.equal((await post('/api/admin',{action:'open-dates',selected:0,dates,mode:'all'})).status,400);
assert.equal((await post('/api/admin',{action:'open-dates',selected:1,dates,mode:'all'})).status,200);
vote=await post('/api/vote',{choices:[0,2]});assert.equal(vote.status,200);
assert.equal((await post('/api/vote',{choices:[1]},vote.cookie)).status,409);assert.equal((await get()).dateTotals,null);
await post('/api/admin',{action:'close-dates'});assert.deepEqual((await get()).dateTotals,[1,0,1]);
const denied=await fetch(base+'/api/admin',{method:'POST',headers:{Origin:'http://other-site','Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,403);
const remote=await fetch(base+'/api/admin',{method:'POST',headers:{Host:'192.168.1.225:3097',Origin:'http://192.168.1.225:3097','Content-Type':'application/json'},body:'{}'});assert.equal(remote.status,403);
assert.equal((await post('/api/admin',{action:'reset'})).status,400);
const oldId=(await get()).pollId;
assert.equal((await post('/api/admin',{action:'reset',confirm:true})).status,200);
assert.equal((await get()).phase,'setup');assert.equal((await get()).dateCount,0);assert.notEqual((await get()).pollId,oldId);
await post('/api/admin',{action:'load-demo',confirm:true});
assert.equal((await get()).demo,true);assert.equal((await get()).nominationCount,10);
assert.equal((await post('/api/vote',{venue:'Sample: Riverside Bistro'},nomination.cookie)).status,200);
assert.equal((await get()).nominationCount,11);
await post('/api/admin',{action:'close-nominations'});
assert.equal((await post('/api/admin',{action:'open-shortlist',selected:[0,1,2,3,4]})).status,200);
assert.equal((await get()).venueCount,10);
assert.equal((await post('/api/vote',{choices:[0]})).status,200);
await post('/api/admin',{action:'close-venue'});
await post('/api/admin',{action:'open-dates',selected:0,dates,mode:'all'});
assert.equal((await get()).dateCount,10);
assert.equal((await post('/api/vote',{choices:[0,1,2]})).status,200);assert.equal((await get()).dateCount,11);
await post('/api/admin',{action:'reset',confirm:true});
assert.equal((await get()).demo,false);assert.equal((await get()).nominationCount,0);assert.equal((await get()).venueCount,0);assert.equal((await get()).dateCount,0);
await post('/api/admin',{action:'open-nominations'});
for(const venue of ['A','B','C'])await post('/api/vote',{venue});
await post('/api/admin',{action:'close-nominations'});
await post('/api/admin',{action:'open-shortlist',selected:[0,1,2]});
let firstVote=await post('/api/vote',{choices:[0]});await post('/api/vote',{choices:[1]});
await post('/api/admin',{action:'close-venue'});
assert.deepEqual((await get()).venueLeaders,[0,1]);
assert.equal((await post('/api/admin',{action:'open-dates',selected:0,dates,mode:'all'})).status,409);
await post('/api/admin',{action:'open-runoff'});
assert.equal((await get()).venueRound,2);assert.equal((await get()).venueCount,0);
assert.deepEqual((await get()).venueOptions,[0,1]);
assert.equal((await post('/api/vote',{choices:[2]})).status,400);
let runoffVote=await post('/api/vote',{choices:[0]},firstVote.cookie);assert.equal(runoffVote.status,200);
assert.equal((await post('/api/vote',{choices:[1]},runoffVote.cookie)).status,409);
await post('/api/vote',{choices:[1]});await post('/api/admin',{action:'close-venue'});
await post('/api/admin',{action:'open-runoff'});assert.equal((await get()).venueRound,3);
await post('/api/vote',{choices:[1]});await post('/api/admin',{action:'close-venue'});
assert.deepEqual((await get()).venueLeaders,[1]);
await post('/api/admin',{action:'open-dates',selected:1,dates,mode:'all'});
await post('/api/vote',{choices:[0,1]});await post('/api/admin',{action:'close-dates'});
assert.equal((await get()).phase,'date-tied');assert.deepEqual((await get()).dateLeaders,[0,1]);
await post('/api/admin',{action:'open-runoff'});assert.equal((await get()).dateCount,0);
assert.equal((await post('/api/vote',{choices:[0,1]})).status,400);
assert.equal((await post('/api/vote',{choices:[2]})).status,400);
await post('/api/vote',{choices:[0]});await post('/api/vote',{choices:[1]});
await post('/api/admin',{action:'close-dates'});assert.equal((await get()).phase,'date-tied');
await stop();await start();assert.deepEqual((await get()).dateLeaders,[0,1]);
await post('/api/admin',{action:'open-runoff'});assert.equal((await get()).dateRound,3);
await post('/api/vote',{choices:[1]});await post('/api/admin',{action:'close-dates'});
assert.equal((await get()).phase,'closed');assert.deepEqual((await get()).dateLeaders,[1]);
console.log('Passed: venue and date runoffs, repeated ties, runoff eligibility and restart persistence, frontend syntax, three-round flow, nomination grouping, top-five ties, winner enforcement, hidden totals, duplicate rejection, restart persistence, closed rounds, organiser restrictions.');
}finally{if(child&&child.exitCode===null)await stop();fs.rmSync(dir,{recursive:true,force:true});}
